### ISSUE TITLE
Make integration for HomeAssistant

### ISSUE THREAD

**Issue by requiemmg** [IngmarStein/mielesolar#12]
This module would perfectly fit with Home Assistant. There is a Miele integration already which does not yet support SmartGrid-Options: https://github.com/astrandb/miele

Maybe this could be integrated/forked?

**Comment by IngmarStein** [comment]
This sounds like a feature request for https://github.com/astrandb/miele, tbh :)

**Comment by requiemmg** [comment]
I know and this is why I asked him first in the HA community forum via DM, but he doesn't happen to have interest (and a Solaredge PV) in that. So I thought to ask here ;-)

BTW, weather here has been ugly the recent weeks; I had no opportunity to test if the running modules is really starting the Miele devices....

**Comment by requiemmg** [comment]
Any Chance you might actually realize this? I have a single pi running for this script only, woukd be so nice to transfer it. Unfortunately, no other machine with VM capabilities...

**Comment by requiemmg** [comment]
I managed to run this on my HA system using portainer for now. Only thing is that HAOS doesnt like non-HA containers and marks this in the logs. I can live with that 😉
