### ISSUE TITLE
Add delay option

### ISSUE THREAD

**Issue by requiemmg** [IngmarStein/mielesolar#29]
Just had the following situation:

It's a rainy/cloudy day today, the battery is empty and the solar production is low. I set the dishwasher and two washing machines to "SmartStart" after loading them. The devices all require almost similar power, so it doesn't make a difference if I use the auto option or the devices.json.

When a cloud moved away, the solar production jumped for a few minutes, enough to hit the trigger value. 
All 3 machines were started in a second, but as they need a few minutes to hit their real consumption (influx of water before heating) they now exceed the solar production a lot.

How about a delay option to be set in seconds in the command line options so that the program waits e.g. 300 seconds before triggering a second device?

**Comment by IngmarStein** [comment]
As mentioned in #9, the power consumption of those devices is hard to predict and depends on factors like the program chosen for washing machines. I hope the new `-delay` flag allows you to find a value which works well for you.

That said, the current logic for triggering devices is also very optimistic: once a device is waiting, we start polling the meter (at the same polling interval) and as soon as the threshold is hit, the start signal is emitted. It would probably be better to monitor the meter continuously and emit the start signal if the surplus was above a threshold for some configurable amount of time. I refrained from doing so for simplicity and to reduce network traffic to the inverter.

**Comment by requiemmg** [comment]
Thanks! Yes, of course you are right. But even with a more sophisticated approach, there will be a day when your devices are running and rain begins to fall. All in all, this tool saves a lot of money with a lot of comfort :-)

**Comment by IngmarStein** [comment]
Yeah, it will never be perfect until we can predict the local weather with 100% accuracy :)
