### ISSUE TITLE
Delayed start

### ISSUE THREAD

**Issue by requiemmg** [IngmarStein/mielesolar#51]
Hi,

I switched from running the native app to running it in a docker container. Works good.
Only thing I noticed: When no machines are running and the conditions for a smartstart trigger are met, the first start is delayed by the chosen delay interval (300 sec) though it could as well start immediately. Not a big issue, just wanted to mention it.

**Comment by IngmarStein** [comment]
Couldn't you just pass `-delay 0` (or via environment `DELAY=0`) to disable the delay?
