### ISSUE TITLE
Handling of EV chargers

### ISSUE THREAD

**Issue by requiemmg** [IngmarStein/mielesolar#52]
Hi,

since last year, I now have my electric vehicle. Of course I want to use the solar power to charge it, but I would like it to charge from the surplus power only if possible. Now, this of course causes all the power to go into the car, so the inverter will not see excess power going to the grid or battery.
And of course there are several different types of wallboxes or other chargers, so I wonder (and have limited ideas) if there is any value you could use to determine this and prefer starting washing machines etc.
One idea would be to push values via MQTT. But you would actually need at least 2 values: Charging mode (and this will be different in naming over several manufacturers) and charging power. Else, if there is no excess solar power and you choose "charge from grid" bc you need your car charged, this would lead to triggering a machine start.

Any ideas on that? or too much to work?
If I had the possibility to trigger the machine's start from Home Assistant (which I do not have) I could simply replace everything through automations, as all values (PV, machines, wallbox, car) are present there....

**Comment by IngmarStein** [comment]
Hi,

it looks like you now want a real Home Energy Management System (HEMS) which allows you to prioritize certain energy consumers over others. mielesolar is not that - it just looks at the remaining surplus and utilizes that for Miele devices. In other words, it's always the lowest priority.

Home Assistant, Solar Manager, and others allow you to do what you describe.
