### ISSUE TITLE
Add threshold value to start all devices

### ISSUE THREAD

**Issue by requiemmg** [IngmarStein/mielesolar#9]
Currently, advanced config allows to start different devices in an order when a set value of surplus solar power is reached.

I have 2 washing machines, 1 tumble dryer and a dishwasher. If I set realistic values for peak power consumption, the last device would never start (~2,5kW for washing machines, ~1,4 kW for dishwasher, ~0,6 kW for Tumble dryer). Of course I can set lower values, but that would result in too early starts when just one machine is programmed. Further, the machines do not need peak power during all the time.
So, maybe we can have an option to start all machines at once when a given threshhold value is reached. Or have 2 values to group machines (e.g. put one high- and one low-consuming machine in a group) and start groupwise.

**Comment by IngmarStein** [comment]
The configuration file is ordered and you can leverage that to set priorities. For example, you could list the tumble dryer as the first device to ensure that it's always triggered first, even if there is not enough surplus power to trigger all devices.
Does that work for your use case?

Household appliances are much harder to schedule compared to devices with contiguous power needs such as wallboxes or heating systems as they can't be started & stopped at will and have highly variable power consumption (as you said). The `auto` flag is meant as a simple compromise: it allows to start devices one after another as the surplus increases (e.g. in the morning) and not create (too) high peaks which could happen when starting everything at the same time.

That said, I'm open to making the auto mode configurable to either start all devices when the specified surplus is available or just one (the current behavior), if you'd like to experiment with what works better in your setup.

**Comment by requiemmg** [comment]
Wow, you are FAST :-) Thanks a lot.
